// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQkn3qbz3YAj4QjVjS6ODx4YCpHlecoXE',
    appId: '1:741842595081:web:49d46a8b86369036e377d8',
    messagingSenderId: '741842595081',
    projectId: 'projectiti-5076d',
    authDomain: 'projectiti-5076d.firebaseapp.com',
    storageBucket: 'projectiti-5076d.appspot.com',
    measurementId: 'G-8TD2WGJK3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6BrDQ27X2HnN_9oiHtpJshTiQr_mVDQ',
    appId: '1:741842595081:android:3dc786e83190054ae377d8',
    messagingSenderId: '741842595081',
    projectId: 'projectiti-5076d',
    storageBucket: 'projectiti-5076d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyDLFIPP9WOVX-HzflvmzdQ69EE5TgX38',
    appId: '1:741842595081:ios:aa0e59ffd4004a05e377d8',
    messagingSenderId: '741842595081',
    projectId: 'projectiti-5076d',
    storageBucket: 'projectiti-5076d.appspot.com',
    iosBundleId: 'com.example.projectiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyDLFIPP9WOVX-HzflvmzdQ69EE5TgX38',
    appId: '1:741842595081:ios:aa0e59ffd4004a05e377d8',
    messagingSenderId: '741842595081',
    projectId: 'projectiti-5076d',
    storageBucket: 'projectiti-5076d.appspot.com',
    iosBundleId: 'com.example.projectiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQkn3qbz3YAj4QjVjS6ODx4YCpHlecoXE',
    appId: '1:741842595081:web:37d72923389dab8ae377d8',
    messagingSenderId: '741842595081',
    projectId: 'projectiti-5076d',
    authDomain: 'projectiti-5076d.firebaseapp.com',
    storageBucket: 'projectiti-5076d.appspot.com',
    measurementId: 'G-6QVLKSNGNS',
  );
}
